version = 1
root = "."
include = [
  "contracts/GrokmeArena.sol",
  "contracts/GrokmeArenaTrophy.sol",
  "contracts/mainnet/GrokNFT.sol"
]

[detectors]
exclude = [
  "sends-ether-away-without-checking-address",
  "reentrancy-state-change"
]
